import { readFileSync } from "node:fs";
import { strict as assert } from "node:assert";

const html = readFileSync(new URL("../index.html", import.meta.url), "utf8");

assert.match(html, /<canvas id="shape-editor"/, "Custom bokeh shape editor canvas is present");
assert.match(html, /const SHAPE_TEXTURE_SIZE = 256/, "Custom bokeh mask uses 256x256 detail");
assert.match(html, /width="256" height="256"/, "Shape editor canvas stores a 256x256 mask");
assert.match(html, /data-shape-preset="default"/, "Default procedural aperture preset is present");
assert.match(html, /data-shape-preset="circle"/, "Circle shape preset is present");
assert.match(html, /data-shape-preset="ellipse"/, "Ellipse shape preset is present");
assert.match(html, /data-shape-preset="rectangle"/, "Rectangle shape preset is present");
assert.match(html, /data-shape-preset="hexagon"/, "Hexagon shape preset is present");
assert.match(html, /data-shape-preset="star"/, "Star shape preset is present");
assert.match(html, /data-shape-preset="anamorphic"/, "Anamorphic slit preset is present");
assert.match(html, /data-shape-preset="ring"/, "Donut/ring preset is present");
assert.match(html, /data-param="shapeRotation"/, "Shape base can be rotated before further drawing");
assert.match(html, /data-param="shapeScale"/, "Shape base can be scaled before further drawing");
assert.match(html, /id="shape-draw-color"/, "Free drawing can choose brush color");
assert.match(html, /data-draw-tool="paint"/, "Free drawing includes a paint tool");
assert.match(html, /data-draw-tool="black"/, "Free drawing can paint black energy-blocking texture");
assert.match(html, /data-draw-tool="erase"/, "Free drawing includes an eraser tool");
assert.match(html, /id="shape-import"/, "Black-background bokeh image import is present");
assert.match(html, /accept="image\/\*"/, "Shape importer accepts image files");
assert.match(html, /<canvas id="shape-crop"/, "Imported bokeh images can be cropped online");
assert.match(html, /id="shape-apply-crop"/, "Crop result can be applied to the bokeh mask");
assert.match(html, /cropBoxSize/, "Image crop defaults to a 1:1 square box");
assert.match(html, /function drawCropPreview/, "Imported images render into a crop preview");
assert.match(html, /function applyImageCropToShape/, "Cropped image is converted into the bokeh mask");
assert.match(html, /preserveImportedBokehTexture/, "Imported bokeh images preserve RGB texture instead of flattening to shape only");
assert.match(html, /importedShapeTextureCanvas/, "Imported bokeh texture is retained as a transformable base source");
assert.match(html, /drawImportedShapeBase/, "Imported bokeh texture can be redrawn with rotation and scale");
assert.doesNotMatch(html, /imageData\.data\[i\] = luminance;\s*imageData\.data\[i \+ 1\] = luminance;\s*imageData\.data\[i \+ 2\] = luminance;/s, "Imported bokeh texture is not flattened into grayscale channels");
assert.match(html, /function drawShapePreset/, "Shape presets draw into the editable mask");
assert.match(html, /function redrawShapeBase/, "Shape base transform can be reapplied without losing the base preset model");
assert.match(html, /currentShapePreset === "default"/, "Default mode is tracked separately from texture-mask presets");
assert.match(html, /function drawOnShapeEditor/, "Pointer drawing can modify the custom bokeh mask");
assert.match(html, /currentDrawTool === "erase"/, "Drawing logic supports erasing from the custom texture layer");
assert.match(html, /currentDrawTool === "black"/, "Drawing logic supports black texture strokes");
assert.match(html, /shapeTextureVersion/, "Shape edits are versioned for renderer upload");
assert.match(html, /shapeMaskTexture = device\.createTexture/, "WebGPU owns a texture for the custom bokeh mask");
assert.match(html, /writeTexture/, "WebGPU uploads the edited shape canvas bytes as a texture");
assert.match(html, /@group\(0\) @binding\(0\) var shapeMaskSampler/, "Bokeh shader receives a mask sampler");
assert.match(html, /@group\(0\) @binding\(1\) var shapeMaskTex/, "Bokeh shader receives a mask texture");
assert.match(html, /textureSampleLevel\(shapeMaskTex, shapeMaskSampler/, "Bokeh shader samples the custom shape mask");
assert.match(html, /let proceduralMask = apertureMask\(input\.local, input\.lens\.x, input\.lens\.y\)/, "Default bokeh uses procedural aperture blades and roundness");
assert.match(html, /select\(proceduralMask, textureMask, input\.shapeMode > 0\.5\)/, "Shader switches between default procedural aperture and custom texture mask");
assert.match(html, /shapeSample\.rgb/, "Bokeh shader uses the imported texture color channels");
assert.match(html, /let textureMask = max\(max\(shapeSample\.r, shapeSample\.g\), shapeSample\.b\)/, "Bokeh texture energy is derived from soft image luminance");
assert.match(html, /function applyCustomShapeClip/, "Canvas fallback clips bokeh discs with the custom mask");
assert.match(html, /function applyCustomShapeTexture/, "Canvas fallback can apply imported bokeh texture detail");
