import { readFileSync } from "node:fs";
import { strict as assert } from "node:assert";

const html = readFileSync(new URL("../index.html", import.meta.url), "utf8");

assert.match(html, /data-param="motionAmount"/, "Bokeh motion amount control is present");
assert.match(html, /data-param="motionSpeed"/, "Bokeh motion speed control is present");
assert.match(html, /data-param="flickerAmount"/, "Bokeh flicker amount control is present");
assert.match(html, /params\.motionAmount/, "Renderer uses the bokeh motion parameter");
assert.match(html, /params\.motionSpeed/, "Renderer uses the bokeh motion speed parameter");
assert.match(html, /params\.flickerAmount/, "Renderer uses the bokeh flicker parameter");
assert.match(html, /function lightMotionOffset/, "Per-light motion offsets are derived deterministically");
assert.match(html, /function lightTwinkle/, "Per-light flicker/twinkle is derived deterministically");
assert.match(html, /const animationSpeed = Math\.max\(0\.25, Math\.min\(4, params\.motionSpeed\)\)/, "Motion speed is clamped to a previewable physical range");
assert.match(html, /0\.012 \* motionAmount/, "Motion amplitude is large enough to preview without export");
assert.match(html, /flickerAmount:\s*0\.85/, "Default flicker is intentionally strong for live preview");
assert.match(html, /1\.15 \* flickerAmount/, "Flicker has a large intensity range for obvious bokeh pulsing");
assert.match(html, /resolveLightOpacity\(light, baseAlpha\) \* twinkle/, "Flicker is applied after base alpha clamping so bright lights visibly pulse");
assert.match(html, /id="export-frame"/, "Single-frame export button is present");
assert.match(html, /id="export-video"/, "Video export button is present");
assert.match(html, /role="button">Record MP4<\/a>/, "Video export starts with an explicit Record MP4 control");
assert.match(html, /function exportFrame/, "Single-frame PNG export is implemented");
assert.match(html, /canvas\.toBlob/, "Frame export captures the rendered canvas");
assert.match(html, /function exportVideo/, "Video export is implemented");
assert.match(html, /const recordCanvas = document\.createElement\("canvas"\)/, "Video export avoids capturing the live WebGPU canvas directly");
assert.match(html, /function mirrorLiveCanvasFrame/, "Video export mirrors the live rendered canvas into the recording canvas");
assert.match(html, /recordCtx\.drawImage\(canvas,\s*0,\s*0,\s*width,\s*height\)/, "Video export records the same pixels shown in the WebGPU preview");
assert.match(html, /recordCanvas\.captureStream\(30\)/, "Video export captures an animated 30fps 2D canvas stream");
assert.doesNotMatch(html, /const stream = canvas\.captureStream\(30\)/, "Video export should not capture the live WebGPU canvas because it can crash embedded browsers");
assert.doesNotMatch(html, /function renderVideoExportFrame/, "Video export should not re-render a lower-fidelity fallback frame for MP4 output");
assert.match(html, /function chooseMp4MimeType/, "Video export chooses an MP4 recorder MIME type");
assert.match(html, /new MediaRecorder/, "Video export records the canvas stream");
assert.match(html, /let pendingVideoExport = null/, "Video export keeps async recorder output until the user can save it");
assert.match(html, /MP4 ready - click Save MP4/, "Video export tells the user where the save action appears");
assert.match(html, /function savePendingVideoExport/, "Video export saves the completed MP4 from a direct user gesture");
assert.match(html, /showSaveFilePicker/, "Video export uses the File System Access save picker when downloads are blocked");
assert.match(html, /exportVideoButton\.href = pendingVideoExport\.url/, "Ready MP4 is exposed as a real user-clickable download link");
assert.match(html, /event\.preventDefault\(\)/, "Video export prevents anchor navigation only while starting a recording");
assert.match(html, /let lastReadoutState = null/, "Export status can refresh the readout outside the render loop");
assert.match(html, /renderReadout\(lastReadoutState\.width, lastReadoutState\.height, lastReadoutState\.count, lastReadoutState\.mode\)/, "Export status changes update the visible readout immediately");
assert.doesNotMatch(html, /Saved MP4/, "Video export should not claim completion when the host browser may block downloads");
assert.match(html, /video\/mp4/, "Video export records MP4 output");
assert.doesNotMatch(html, /video\/webm/, "Video export does not fall back to WebM");
